server:
  port: 8001
  servlet:
    context-path: /


hikari:
  url: jdbc:mysql://localhost:3306/distributeMall?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
  username: root
  password: Bendan120!

mybatis:
  config-location: classpath:mybatis-config.xml
  table:
    auto: update
  model:
    pack: me.marmoo.common.domain
  database:
    type: mysql
  mapper-locations: classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
redis:
  password: 123456
spring:
  data:
    mongodb:
      uri: mongodb://admin:123456@114.55.64.54:27017/distributePo
  #      host: 114.55.64.54
#      port: 27017
#      password: 123456
#      username: admin
#     # authentication-database: distributePo
#      database: distributePo
